alias version='lsb_release -a'
alias start='echo "use open"'
alias ngoding='. ~/code.sh'
alias nugas='. ~/nugas.sh'
alias android='/media/fauzan-radji/Data/__jetbrains-tools/android-studio/bin/studio'
alias notify='notify-send -u critical'
alias please='sudo'
alias files='open /media/fauzan-radji/Data/'
alias clera='clear'
alias switch-version='update-alternatives --config'

alias phpunit='vendor/bin/phpunit'
